<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="mixkit-alarm-tone-996.wav\**" />
    <Content Remove="mixkit-alarm-tone-996.wav\**" />
    <EmbeddedResource Remove="mixkit-alarm-tone-996.wav\**" />
    <None Remove="mixkit-alarm-tone-996.wav\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
    <None Include="wwwroot\css\Autocomplete.css" />
    <None Include="wwwroot\Sounds\mixkit-bell-notification-933.wav" />
    <None Include="wwwroot\Sounds\mixkit-positive-notification-951.wav" />
    <None Include="wwwroot\Sounds\mixkit-toy-robot-alert-2815.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildWebCompiler2022" Version="1.14.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorComponents\BlazorComponents.csproj" />
    <ProjectReference Include="..\PokerLibrary\PokerLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\Sounds\mixkit-bell-notification-933.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Sounds\mixkit-positive-notification-951.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Sounds\mixkit-toy-robot-alert-2815.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="pokerDb.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
